# Generated by Django 2.2.5 on 2019-09-16 12:24

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('review', '0001_initial'),
        ('professions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_moderator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='offender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review.Offender'),
        ),
        migrations.AddField(
            model_name='review',
            name='scope_of_cooperation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_scope_cooperation', to='professions.ProfessionalArea'),
        ),
        migrations.AddField(
            model_name='phone',
            name='offender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offender_phone', to='review.Offender'),
        ),
        migrations.AddField(
            model_name='offender',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.City'),
        ),
        migrations.AddField(
            model_name='offender',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Country'),
        ),
        migrations.AddField(
            model_name='offender',
            name='traits',
            field=models.ManyToManyField(blank=True, related_name='offenders', to='review.Trait'),
        ),
        migrations.AddField(
            model_name='answer',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='review.Review'),
        ),
        migrations.AddIndex(
            model_name='shameboard',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='review_sham_created_c68d7f_brin'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['added_at'], name='review_phon_added_a_fae89e_brin'),
        ),
        migrations.AddIndex(
            model_name='offender',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='review_offe_created_942a7d_brin'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='review_answ_created_4de601_brin'),
        ),
    ]
