# Generated by Django 2.2.4 on 2019-09-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20190917_0857'),
        ('review', '0003_auto_20190917_0646'),
    ]

    operations = [
    ]
