# Generated by Django 2.2.4 on 2019-09-18 11:47

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_merge_20190918_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='review_revi_created_818bfd_brin'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='review_feed_created_1e74c7_brin'),
        ),
    ]
