# Generated by Django 2.2.4 on 2019-09-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20190918_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='payment_uid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
