# Generated by Django 2.2.4 on 2019-10-01 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0006_auto_20191001_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='payment_uid',
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='answer_author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shameboard',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='shame_board_author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
