# Generated by Django 2.2.4 on 2019-10-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_review_payment_uid'),
        ('review', '0007_auto_20191001_0415'),
    ]

    operations = [
    ]
