# Generated by Django 2.2.4 on 2019-10-04 16:12

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_merge_20191003_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffenderLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('code', models.SmallIntegerField(blank=True, choices=[(0, 'LinkedIn'), (1, 'Facebook'), (2, 'VK'), (3, 'HeadHunter'), (5, 'Instagram'), (6, 'Twitter'), (7, 'Telegram'), (8, 'Viber'), (9, 'Discord'), (10, 'Other')], null=True, verbose_name='Link code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offender_link', to='review.Offender')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='offenderlink',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='review_offe_created_4d8c74_brin'),
        ),
    ]
