# Generated by Django 2.2.5 on 2019-09-16 12:24

from django.db import migrations, models
import django.db.models.deletion
import uploads.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=uploads.utils.upload_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_proof_docs', to='review.Answer')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_proof_docs', to='review.Review')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ('uploaded_at',),
            },
        ),
    ]
