# Generated by Django 2.2.5 on 2019-09-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('professional_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_area', to='professions.ProfessionalArea')),
            ],
        ),
    ]
